# Generated by Django 4.1.1 on 2022-09-28 17:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('url', models.CharField(max_length=999, verbose_name='Url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
