# Generated by Django 4.1.1 on 2022-09-28 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.FileField(default=django.utils.timezone.now, upload_to='img/'),
            preserve_default=False,
        ),
    ]
