# Generated by Django 4.1.1 on 2022-10-02 12:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0002_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kedi Türü')),
            ],
        ),
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(0, 'Dişi'), (1, 'Erkek')], max_length=1)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Hakkında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.FileField(upload_to='img/')),
                ('cat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backsite.catstype')),
            ],
        ),
    ]
