# Generated by Django 4.1.1 on 2022-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0003_catstype_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_mailpage',
            field=models.BooleanField(default=False, verbose_name='Ana Sayfa'),
        ),
        migrations.AddField(
            model_name='cats',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='cats',
            name='is_mailpage',
            field=models.BooleanField(default=False, verbose_name='Ana Sayfa'),
        ),
    ]
