# Generated by Django 4.1.1 on 2022-11-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0004_blog_is_active_blog_is_mailpage_cats_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='is_mailpage',
            new_name='is_mainpage',
        ),
        migrations.RenameField(
            model_name='cats',
            old_name='is_mailpage',
            new_name='is_mainpage',
        ),
    ]
