# Generated by Django 4.1.1 on 2022-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backsite', '0005_rename_is_mailpage_blog_is_mainpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Dişi'), (2, 'Erkek')]),
        ),
    ]
